### ISSUE TITLE
Can not run with omniconfig==0.1.7

### ISSUE THREAD

**Issue by Summer-Summer** [mit-han-lab/deepcompressor#22]
I have run into issues when running the following CLI, and I find that if I use omniconfig==0.1.5, this problem is solved.
I guess, there are some problems within omniconfig==0.1.7?
What I observed is that "parser.parse_known_args(args)" returned four items within omniconfig==0.1.7, but we are only expecting three items.

python -m lmquant.llm.run \
    configs/llm.yaml configs/qoq/gchn.yaml \
    --model-name llama2-7b --model-path /PATH/TO/LLAMA2-7B \
    --smooth-xw-alpha 0 --smooth-xw-beta 1
    --smooth-yx-alpha 0.5 --smooth-yx-beta 0

**Comment by synxlin** [comment]
Hi,

If you installed `lmquant-v0.0.0`, please fix `ominconfig` package to version `0.1.5`.
